apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: auto-auction-recursive
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Eoin-Byrne/SCRImages.git
    targetRevision: HEAD
    path: apps
    directory: 
       recurse: true
       include: '*/deployment/*.yaml'
  destination: 
    server: https://kubernetes.default.svc
    namespace: scr
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
