apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  namespace: scr
  name: sas-scr-${sas-scr-published-name}
  labels:
    app: sas-scr-${sas-scr-published-name}
  annotations:
    component-name: sas-scr-${sas-scr-published-name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sas-scr-${sas-scr-published-name}
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 6000
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Pods
        value: 1
        periodSeconds: 60
      - type: Percent
        value: 10
        periodSeconds: 60
      selectPolicy: Max  
