name: Move SCR folders for ArgoCD
on:
  push
jobs:
  Move-Folder-Down:
    name: MoveDown
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - run: if [ -d autoAuction* ]; then cp -r autoAuction*/ apps/; find auto* -delete; fi
      - name: Auto Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        
